import type { DeelvraagContent } from "./types";

export const deelvraag2: DeelvraagContent = {
  slug: "2",
  number: 2,
  title: "De B2B-markt bereiken",
  subtitle: "Hoe de zakelijke markt beter bereiken en benutten, doordeweeks en buiten het hoogseizoen",
  question: "Op welke manier kan Rederij Cascade de B2B-markt beter bereiken en benutten, met name doordeweeks en buiten het hoogseizoen?",
  sections: [
    {
      id: "dv2-probleem",
      title: "Inleiding van het probleem",
      paragraphs: [
        "De omzet van Rederij Cascade is niet goed verdeeld over het jaar heen. De inkomsten zijn afhankelijk van het seizoen. Na de kerstperiode vallen de inkomsten nagenoeg stil omdat de boten grotendeels niet meer varen. Terwijl de vaste lasten gewoon doorlopen. Denk hier aan de loonkosten van het vaste personeel, leningen en belastingen.",
        "In de huidige situatie blijven de boten voor de eerste 4 maanden van het jaar grotendeels stil aan de kade liggen. Er blijft nu een kans liggen, bij de B2B markt, want bedrijven zoeken in het begin van het jaar juist een plek voor bijvoorbeeld een nieuwjaarsborrel of strategische sessies. En omdat bedrijven vaak met grotere groepen zijn die ook catering nodig hebben, kan je een grotere omzet per groep verwachten.",
        "De zakelijke doelgroep van de B2B markt is een goede aanvulling op de huidige activiteiten, vanwege een aantal redenen: Bedrijven plannen hun vergaderingen, teamuitjes, trainingen, klantendagen etc. meestal door de week en juist niet in de zomer. Dit sluit goed aan bij de doelgroep toeristen die juist in het weekend en de zomerperiode een rondvaart boeken. B2B activiteiten hebben vaak een hoger budget per persoon dan recreanten. Bedrijven geven meer geld uit voor catering, techniek en extra services. Bedrijven die tevreden zijn keren regelmatig terug, terwijl een recreant maar een keer een rondvaart zal doen.",
      ],
    },
    {
      id: "dv2-situatie",
      title: "Huidige situatie",
      paragraphs: [
        "Op dit moment richt rederij Cascade zich niet specifiek op de B2B markt. De nadruk ligt op dit moment bij de B2C markt. Dit zorgt voor een hoogseizoen in de warmere maanden en een dip in de koudere maanden.",
        "Om dit probleem aan te pakken moet de basis op orde zijn, en dit is het geval: De infrastructuur is aanwezig, de boten liggen klaar, de juiste vergunningen zijn aanwezig, er is voldoende personeel en het personeel heeft voldoende expertise. Alle boten zijn voorzien van audiovisuele apparatuur, zowel schermen als een geluidsinstallatie. Het bedrijf is in de zomer succesvol genoeg om de winter door te komen. In de winter is er een overschot aan capaciteit: Bedrijfsevenementen hoeven in de winter niet te concurreren met de ticketverkoop.",
        "Er zijn ook verbeterpunten: Er mist een gerichte strategie om de zakelijke markt te bereiken en te overtuigen, momenteel ligt de nadruk nog te veel op de toeristische attractie. Er wordt te weinig genetwerkt en marketing gedaan richting bijvoorbeeld event managers, HR-afdelingen of partyplanners. Zij zijn juist in de eerste paar maanden van het jaar op zoek naar unieke locaties voor hun vergaderingen.",
      ],
    },
    {
      id: "dv2-markt",
      title: "Markt voor zakelijk vergaderen in Limburg",
      paragraphs: [
        "De markt voor congressen en vergaderingen is aanzienlijk. Landelijk lag dit in 2019 op een omzet van € 2.730 miljoen. In de Congres en Vergader Monitor 2024 staat de provinciale spreiding van deelnemende locaties; Limburg is daarin 4%. Dat betekent dat de markt van congressen en vergaderen in Limburg in 2019 € 109 miljoen is.",
        "Het rapport beschrijft dat de markt voor vergaderen en congressen in Limburg kleiner is dan in de Randstad, maar een duidelijk eigen karakter heeft. Limburg richt zich niet op grote aantallen, maar vooral op kwaliteit, rust en inspiratie. De meeste bijeenkomsten bestaan uit vergaderingen, workshops, trainingen en strategische sessies voor kleine en middelgrote groepen (ongeveer 30 tot 150 personen). Grote congressen komen voor, maar zijn niet de belangrijkste markt. Limburg is vooral sterk in meerdaagse bijeenkomsten, waarin inhoud wordt gecombineerd met teambuilding, natuur, water en goed eten.",
        "Veel Limburgse locaties worden gekozen omdat ze anders en inspirerend zijn. Er is nog ruimte voor groei, vooral door betere zichtbaarheid online en door het aanbieden van aantrekkelijke totaal arrangementen.",
        "De Congres- en Vergader Monitor 2024 maakt duidelijk dat het voor Rederij Cascade een grote kans is om zich te gaan richten op de B2B markt. Het goed opzetten van online zichtbaarheid en aanbieden van totaal arrangementen vergroot de kans op succes.",
        "De monitor maakt duidelijk dat bezettingsgraden per locatie sterk verschillen en dat capaciteit een belangrijke factor is. Ook wordt genoemd dat Utrecht met ca. 27% gemiddeld hoger scoort dan andere provincies. Vanuit de monitor lijkt een bezettingsgraad van 20% haalbaar. Uitgaande van 160 beschikbare dagen voor zakelijke evenementen en een bezettingsgraad van 20%, betekent dit 32 zakelijke evenementen per jaar.",
        "Uit de Congres- en Vergader Monitor halen we ook dat zakelijke klanten gemiddeld € 70 tot € 150 per persoon per dag uitgeven voor vergaderingen en workshops. Voor strategische sessies, trainingen & teambijeenkomsten wordt € 150 tot € 250 per persoon per dag uitgegeven.",
        "Een voorzichtige berekening van 32 dagen met zakelijke evenementen voor 75 personen met een gemiddelde uitgave van € 150 per persoon, betekent een extra potentiële omzet voor Rederij Cascade van € 360.000,-.",
      ],
    },
    {
      id: "dv2-concurrentie",
      title: "Concurrentie in Limburg",
      paragraphs: [
        "Rederij Cascade heeft vanuit twee kanten concurrentie in de B2B markt. Aan de ene kant van de markt zijn dat andere rederijen in Limburg, aan de andere kant zijn dat vergaderlocaties op het land. Daar komt de echte concurrentie vandaan.",
        "Andere rederijen zijn: Rederij Stiphout (vaart vanuit Zuid-Limburg en is vooral gericht op toerisme en groepsuitjes, weinig focus op vergaderen en congressen in de B2B markt), Rederij de Corporaal (vaart vanuit Roermond en heeft een sterke focus op rondvaarten, 1 boot voor 54 personen en weinig zakelijke faciliteiten), Maashopper (richt zich op bedrijfs- en familiefeesten en kan tot 200 passagiers vervoeren) en Dutch Cruise Line (vooral gespecialiseerd in meerdaagse riviercruises, noemen de zakelijke markt wel op hun website maar doen weinig op dat gebied).",
        "De echte concurrentie komt niet vanuit het water, maar vanuit vaste vergaderlocaties aan land. Deze locaties zijn speciaal ingericht voor zakelijke bijeenkomsten en sluiten daardoor beter aan op wat bedrijven nodig hebben.",
        "In Limburg zijn er ongeveer 60 tot 100 vergaderlocaties. Deze zijn onder te verdelen in drie segmenten: Functionele vergaderlocaties (~40%), zoals business hotels in Venlo, Heerlen, Maastricht en Roermond — efficiënt, goede AV, goede parkeermogelijkheden, goed bereikbaar, maar weinig beleving. Inspirerende vergaderlocaties met gemiddeld prijsniveau (~50%), zoals beachclubs en kasteelhoeven — bijzondere omgeving, prettige informele sfeer. Exclusieve, high-end vergaderlocaties (~10%), zoals kastelen, musea en retreats — alles draait om beleving en unieke ervaringen.",
        "Rederij Cascade behoort tot de categorie inspirerende vergaderlocaties. Om succesvol te worden in de B2B vergadermarkt is het belangrijk dat Rederij Cascade zich duidelijk onderscheidt van de andere locaties in dit segment.",
      ],
    },
    {
      id: "dv2-zoekgedrag",
      title: "Hoe zoeken klanten naar zakelijke locaties?",
      paragraphs: [
        "Zakelijke opdrachtgevers beginnen hun zoektocht bijna altijd online. Ze oriënteren zich via gespecialiseerde locatieplatforms (zoals Locaties.nl en inspirerendelocaties.nl), zoekmachines (Google), en steeds vaker via AI. Social media speelt in deze fase nauwelijks een rol bij het daadwerkelijk vinden van een locatie. De eerste stap is vooral: \"Welke locaties zijn er die globaal passen bij mijn vraag?\"",
        "In de oriëntatiefase zoeken klanten vooral op functionele randvoorwaarden zoals capaciteit (aantal personen), ligging en reistijd, bereikbaarheid en parkeergelegenheid en type bijeenkomst (vergadering, heisessie, congres, relatie-event). Pas als een locatie aan deze basisvoorwaarden voldoet, wordt zij serieus bekeken.",
        "Wanneer meerdere locaties aan de basiscriteria voldoen, verschuift de aandacht naar beleving: uitstraling van de locatie, omgeving (water, natuur, historisch pand), originaliteit en onderscheidend vermogen. De locatie moet passen bij het doel van de bijeenkomst en het verhaal dat de organisatie wil vertellen. In deze fase winnen inspirerende locaties terrein ten opzichte van standaard vergaderruimtes.",
        "Het onderzoek laat zien dat klanten sterk sturen op duidelijkheid vooraf op het gebied van heldere prijsinformatie, wat wel en niet mogelijk is, beschikbaarheid en duidelijke arrangementen. Gebrek aan transparantie zorgt voor onzekerheid en het afhaken van opdrachtgevers, terwijl openheid juist vertrouwen en meer aanvragen oplevert. Klanten willen snel weten waar ze aan toe zijn.",
        "Beoordelingen, ervaringen van andere klanten en aanbevelingen spelen een belangrijke rol in de definitieve keuze. Social proof verlaagt het gevoel van risico: \"Als andere organisaties hier tevreden waren, zal het voor ons ook goed zijn.\" Locaties met zichtbare reviews en referenties worden sneller gekozen.",
        "Persoonlijk contact blijft belangrijk bij het zoeken naar een locatie. Hoewel de oriëntatie digitaal is, wordt in de selectiefase vaak persoonlijk contact opgenomen, een offerte aangevraagd of een locatiebezoek gepland. Opdrachtgevers hechten veel waarde aan flexibiliteit, meedenken en het nakomen van afspraken. Deze zachte factoren wegen zwaarder dan alleen de prijs.",
        "Binnen dit zoekgedrag heeft Rederij Cascade een sterke uitgangspositie als zij: duidelijk vindbaar is binnen de juiste filters (capaciteit, regio, type event), de beleving van vergaderen op het water helder communiceert, transparant is over mogelijkheden en prijsindicaties, en social proof actief inzet.",
      ],
    },
    {
      id: "dv2-doelgroep",
      title: "Wie boekt een zakelijke locatie?",
      paragraphs: [
        "Uit locatie onderzoek van HighProfile komen de volgende doelgroepen, die zich bezighouden met het boeken van vergaderlocaties: Directie secretaresses, management assistenten (met een ondersteunende rol), Corporate event managers / event manager (werkzaam in het bedrijf), Bureaus / evenementenorganisaties (professionele organisator), ZZP-er (zelfstandige organisator) en overige medewerker bedrijf (bv. eigenaar, HR-medewerker).",
        "Directie secretaresses en managementassistenten zoeken een locatie vooral via Google en hebben minder behoefte aan het verhaal achter de locatie. Corporate event managers vertrouwen vaker op eigen ervaring, besteden het grootste deel van hun werk aan events en nemen meer tijd om locaties te vergelijken en te bezoeken. Medewerkers van evenementenorganisaties zijn het meest grondig: zij starten het vroegst met zoeken, bezoeken de meeste locaties en hechten sterk aan het verhaal achter de locatie. Zzp'ers vormen een aparte groep en gebruiken relatief vaak Facebook, terwijl andere doelgroepen dit kanaal juist minder inzetten.",
        "Secretaresses / assistentes willen snel beslissen en zoeken duidelijk informatie, snelle offertes en zekerheid. (Corporate) event managers zoeken het verhaal achter de locatie en zoeken cases, beoordelingen en een duidelijke propositie. Evenementenbureaus moeten een locatie 'verkopen' aan hun klanten en zoeken pitch-materiaal, namelijk mooie afbeeldingen, unieke kenmerken, transparantie, en het verhaal achter de locatie.",
      ],
    },
    {
      id: "dv2-positionering",
      title: "Positionering Rederij Cascade op B2B markt",
      paragraphs: [
        "Om de B2B markt succesvol op te gaan, moet de Rederij zich duidelijk positioneren. Gezien alle uitgangspunten, de markt, concurrentie en doelgroep stellen we de volgende positionering voor: \"Rederij Cascade is dé vergader- en eventlocatie op het water voor organisaties die focus, verbinding en beleving willen combineren.\"",
        "Rederij Cascade staat voor: Rust en focus (geen afleiding, ideaal voor besluitvorming), Ontzorging (één aanspreekpunt, alles op één locatie, maatwerk) en Beleving met zakelijke impact (geen \"leuk uitje\", maar functionele beleving, ondersteunt zakelijke doelstellingen). Deze 3 pijlers moeten gebruikt worden in alle communicatie, zoals op de website.",
        "De kernbelofte: \"Bij Rederij Cascade vergadert u zonder afleiding, op één plek, met ruimte voor betere gesprekken.\"",
        "De positionering en kernbelofte bepalen onze communicatie. In plaats van termen als 'boottocht met lunch' of 'origineel uitje' spreken we over 'een strategiedag op het water' of 'vergaderen zonder afleiding'. Je bent letterlijk weg van kantoor. Je kunt 'niet ontsnappen'. Dit onderscheidt Rederij Cascade van vergaderlocaties op land. De omgeving op de boot versterkt samenwerking.",
      ],
    },
    {
      id: "dv2-ideeen",
      title: "Ideeën om B2B markt te benutten",
      paragraphs: [
        "De B2B doelgroep is wezenlijk anders dan de markt die Rederij Cascade nu benadert met haar marketing activiteiten. Daarom is het belangrijk om een marketingplan op te stellen voor deze nieuwe doelgroep. In dit plan moeten ook doelstellingen opgenomen worden voor de komende jaren.",
        "Op de website van Rederij Cascade moeten de toeristische activiteiten een even grote plek innemen als de zakelijke bijeenkomsten. Nu zijn de toeristische mogelijkheden prominent aanwezig, en de zakelijke mogelijkheden zijn benoemd als \"ook mogelijk\". De beelden op de website zijn vooral van rondvaarten, diners en feesten. Er is minder aandacht voor zakelijke beelden, zoals vergaderen. Zakelijke beslissers hebben behoefte aan snel overzicht en structuur.",
        "Advies: Maak op de homepage en in het menu een duidelijke aparte propositie voor de zakelijke events. Positioneer zakelijke events niet als \"ook mogelijk\" maar als volwaardige specialisatie. Gebruik hiervoor beelden van zakelijke evenementen. Zorg voor een duidelijke pagina met alle praktische informatie die belangrijk is voor de B2B markt: geschikt voor (vergadering, presentatie, training, relatiedag), capaciteit per schip, faciliteiten aan boord (AV, wifi, break-outs), bereikbaarheid & parkeren. Zorg voor reviews van zakelijke contacten.",
        "Potentiële zakelijke klanten oriënteren zich vaak online voordat zij een locatie boeken. SEO en GEO zorgen ervoor dat Rederij Cascade gevonden wordt. SEO (Search Engine Optimization) zorgt ervoor dat Rederij Cascade hoog in Google verschijnt op zoektermen als vergaderen op het water, zakelijk event Limburg of relatiedag op unieke locatie. GEO (Generative Engine Optimization) richt zich op zichtbaarheid in AI-zoekomgevingen zoals Copilot en ChatGPT.",
        "Secretaresses en managementassistenten spelen vaak een sleutelrol bij de organisatie en locatiekeuze van zakelijke bijeenkomsten. Om hen kennis te laten maken met Rederij Cascade en alle mogelijkheden voor zakelijke events, stellen we voor een kennismakingsmiddag te organiseren.",
        "Aanbod van diensten en services afstemmen op de B2B markt. Zakelijke opdrachtgevers willen snel weten waar ze aan toe zijn. Heldere, kant-en-klare arrangementen verlagen de drempel en versnellen de beslissing. We hebben vijf arrangementen uitgewerkt die aansluiten op verschillende zakelijke doelen — van strategiesessies en heidagen tot relatiedagen, afterwork borrels en productpresentaties.",
        "Persoonlijke benadering klanten en relatieopbouw. In de zakelijke markt van vergaderingen en evenementen is persoonlijk contact een belangrijke succesfactor. Online zichtbaarheid zorgt voor de eerste interesse, maar het is het directe, menselijke contact dat vertrouwen opbouwt en uiteindelijk leidt tot boekingen. Voor Rederij Cascade zou de focus daarom moeten liggen op het actief en persoonlijk benaderen van relevante doelgroepen.",
        "De persoonlijke benadering van deze groep kan via e-mail, LinkedIn en door ze uit te nodigen voor een persoonlijke kennismaking. Ook kan je denken aan het versturen van een nieuwsbrief. Een bestand met de contactgegevens van zakelijke klanten moet opgebouwd worden. Er is een eenvoudig CRM-systeem nodig om de gegevens in bij te houden. Contactgegevens zijn te krijgen via het contactformulier op de website, zoeken op LinkedIn, LinkedIn of Google Adwords campagnes, locatieplatforms en bedrijfsadressen en e-mail aankopen via de Kamer van Koophandel.",
        "Herhaalbezoek en loyaliteit zakelijke klanten bevorderen. Voor Rederij Cascade zijn terugkerende B2B-klanten van grote waarde. Herhaalbezoek leidt tot sterke klantrelaties, goede reviews en hogere omzet. Via het CRM-systeem worden de contactmomenten bijgehouden. Na ieder bezoek kan je een tevredenheidsenquête sturen om te meten wat men ervan vond en om een review of quote te vragen.",
        "Ook kan je denken aan een loyaliteitsprogramma. Klanten ontvangen bij een tweede en/of derde boeking bijvoorbeeld een korting of een upgrade binnen het arrangement. Daarnaast kan ook een referentieprogramma opgezet worden: klanten die Rederij Cascade aanbevelen bij andere organisaties worden beloond met een cadeau of korting.",
        "Samenwerkingen. Door samen te werken met evenementen- en congresbureaus in heel Nederland kan Rederij Cascade meer zakelijke boekingen krijgen. Met deze bureaus worden heldere afspraken gemaakt over doorverwijzingen en een vaste vergoeding per boeking. Zo kunnen evenementenbureaus hun klanten een bijzondere locatie op het water aanbieden, terwijl Rederij Cascade profiteert van een constante stroom nieuwe zakelijke aanvragen.",
        "Zakelijke LinkedIn pagina actief inzetten. Rederij Cascade kan LinkedIn gebruiken om beter zichtbaar te zijn voor bedrijven. Op de pagina worden berichten geplaatst over de arrangementen, eerdere zakelijke bijeenkomsten en praktische informatie. Met foto's en korte updates laat Rederij Cascade zien wat vergaderen en ontmoeten op het water inhoudt. LinkedIn wordt ook gebruikt om in contact te komen met bedrijven, managementassistenten en evenementenbureaus, zodat Rederij Cascade onder de aandacht blijft bij het plannen van zakelijke bijeenkomsten.",
        "Aanbieden extra diensten. Naast de rondvaart, catering en vergaderfaciliteiten, kunnen ook extra diensten aangeboden worden. Zoals een professionele dagvoorzitter of leuke energizers om de groep bij de les te houden. Dit levert extra omzet op en geen risico's: je huurt iemand pas in als je een boeking hebt. Hiervoor moet een netwerk opgebouwd worden van passende dagvoorzitters en aanbieders van energizers.",
      ],
    },
    {
      id: "dv2-afweging",
      title: "Afweging en keuze",
      paragraphs: [
        "Om te bepalen welke acties als eerste opgepakt moeten worden, hebben we alle voorgestelde onderdelen tegen elkaar afgewogen op basis van afweging, impact in tijd of geld, en status of advies. Het resultaat geeft een duidelijke prioritering: onderdelen met hoge prioriteit vormen de basis en moeten direct opgepakt worden, terwijl onderdelen met lage prioriteit pas later in het traject aan bod komen.",
        "Een marketingplan is cruciaal voor het slagen op de zakelijke markt — dit is de basis voor alle stappen die genomen moeten worden. De basis voor dit plan staat al in dit verslag; de impact is alleen tijd. Het marketingplan is inmiddels opgesteld voor het benaderen van de B2B markt (zie bijlage).",
        "Een goede website waar zakelijke klanten makkelijk kunnen vinden wat ze zoeken, is heel belangrijk voor het succes. De website kan aangepast worden door de interne marketing medewerker. Het inzetten van een professionele fotograaf voor zakelijke foto's zal eenmalig een lage kostenpost zijn, geschat op € 1.500,-. Dit heeft een hoge prioriteit — advies om dit direct door te voeren.",
        "Goede SEO en GEO zorgen voor goede vindbaarheid. Als je de website aanpast op de zakelijke markt, dan moet deze ook vindbaar zijn. Eenmalig inhuren van professionals om alles in te stellen en de marketing medewerker te instrueren. Kosten geschat op € 1.500 – € 2.000,-. Deze optie heeft medium prioriteit en kan ook op een later moment nog ingezet worden.",
        "Een kennismakingsmiddag voor secretaresses en assistenten werkt uitstekend: niets werkt zo goed als een persoonlijke kennismaking met de vloot. Dit vergroot het vertrouwen en maakt de drempel lager om te boeken. De kosten zijn voor Rederij Cascade alleen de inkoopkosten van catering en personeel, plus een tijdsinvestering in voorbereidingen (geschat op 30 uur). Medium prioriteit — een uitnodiging en programma is al uitgewerkt (zie bijlage).",
        "Zakelijke klanten hebben andere behoeften dan toeristische klanten. Belangrijk om zakelijke arrangementen op te stellen. Dit gaat alleen om een tijdsinvestering: de voorgestelde arrangementen moeten uitgewerkt worden in de procedures van de vloot. Dit heeft hoge prioriteit. In dit plan staat een voorstel voor 5 arrangementen.",
        "B2B-klanten hechten waarde aan persoonlijk contact en een vast aanspreekpunt. Het opbouwen van een bestand met zakelijke klanten kost tijd. Dit gaat in eerste instantie om een investering in tijd van de sales- en marketingafdeling. Kosten voor een CRM-systeem zijn laag. Campagnes om adressen te verzamelen kunnen wel oplopen (€ 2.000 – € 5.000 per jaar). Dit heeft een hoge prioriteit — een goede persoonlijke benadering leidt tot meer klanten en herhaalbezoeken.",
        "Terugkerende klanten leveren hogere omzet en lagere acquisitiekosten op. Beperkte kosten voor kleine incentives of loyaliteitsvoordelen, plus een tijdsinvestering in relatiebeheer. Dit heeft een lage prioriteit en kan als een van de laatste acties opgepakt worden.",
        "Samenwerking met evenementen- en congresbureaus vergroot het bereik en zorgt voor nieuwe klanten. Dit vergt vooral tijd — het heeft langere tijd nodig om een goede samenwerking op te bouwen. Wellicht ook wat lage kosten voor specifiek marketingmateriaal dat de bureaus nodig hebben voor hun klanten. Medium prioriteit: het kan veel opleveren maar kost ook veel tijd. Als start hebben we alvast een lijst met congres- en evenementenbureaus opgesteld en een e-mail om ze te benaderen.",
        "LinkedIn is een belangrijk communicatiekanaal voor zakelijke klanten. Het gaat hier vooral om een investering in tijd van de marketing medewerker. Op de langere termijn misschien kosten voor een LinkedIn advertentiecampagne. Medium prioriteit: ondersteunend aan de website en het opbouwen van een netwerk duurt lang.",
        "Extra diensten zoals professionele sprekers of teamactiviteiten verhogen de waarde per boeking. Hierbij gaat het om inkoopkosten die je kunt doorverkopen aan de klant — geen investering nodig, alleen tijd om goede diensten uit te zoeken. Lage prioriteit: een goede kans om de omzet te vergroten als de andere zaken op orde zijn.",
      ],
    },
    {
      id: "dv2-conclusie",
      title: "Conclusie",
      paragraphs: [
        "De B2B-markt is een grote kans voor Rederij Cascade. Met een duidelijke focus op zakelijke klanten, een overzichtelijke website en heldere arrangementen kan Rederij Cascade meer zakelijke boekingen aantrekken.",
        "Door persoonlijk contact op te bouwen met bedrijven ontstaat vertrouwen en herhaalbezoek. Dit past goed bij de beschikbare capaciteit in de wintermaanden en zorgt voor hogere bestedingen per groep.",
        "Zo wordt de omzet beter over het jaar verdeeld en wordt het bedrijf minder afhankelijk van het toeristische seizoen.",
      ],
    },
  ],
};
