import type { DeelvraagContent } from "./types";

export const deelvraag3: DeelvraagContent = {
  slug: "3",
  number: 3,
  title: "Personeel aantrekken en behouden",
  subtitle: "Hoe voldoende en geschikt personeel vinden in de huidige arbeidsmarkt",
  question: "Hoe kan Rederij Cascade in de huidige arbeidsmarkt voldoende en geschikt personeel aantrekken en behouden voor functies zoals kapiteins, bedienend personeel, keukenpersoneel en afwassers?",
  sections: [
    {
      id: "dv3-probleem",
      title: "Inleiding van het probleem",
      paragraphs: [
        "Met de sterke groei van het bedrijf komt natuurlijk ook een hogere vraag naar arbeid. Zonder personeel kan onze onderneming immers niet draaien en zullen we niet in staat zijn om de gasten de ervaring te bieden die wij graag zouden willen geven.",
        "Doordat de huidige markt zeer krap is kan het moeilijk zijn om geschikt personeel te vinden, vooral voor een onderneming die zeer arbeidsintensief is en dus weinig loonruimte heeft. Als wij torenhoge lonen moeten betalen aan onze werknemers, dan zijn wij genoodzaakt deze gestegen arbeidskosten door te berekenen aan de klant. Dit zal resulteren in een flinke daling in vraag omdat onze sector, horeca/ dagrecreatie, zeer prijselastisch is.",
        "Buiten de situatie van de arbeidsmarkt is het voor de horecabranche erg lastig om personeel te vinden. Doordat de vraag naar ons product erg fluctueert van de zomer tot de winter, kunnen wij onze medewerkers niet jaarrond een bepaald aantal uren aanbieden. Het merendeel van de werknemers zal dus arbeid verrichten op basis van een oproepcontract. Het nadeel van arbeid op basis van een oproepcontract voor de werkgever is dat de werknemer veel rechten heeft op het gebied van flexibiliteit en beschikbaarheid. Het is dus altijd maar de vraag of je genoeg personeel beschikbaar hebt op de piekdagen.",
        "Een ander nadeel is dat de volwassenen, die vaak meer ervaring hebben, geen genoegen nemen met een oproepcontract. Zij moeten tenslotte jaar rond hun woning en boodschappen kunnen betalen, niet alleen in de zomer. Omdat wij vanwege de seizoensafhankelijke vraag niet altijd evenveel vraag hebben, kunnen wij niet iedereen een vast contract aanbieden. Hoewel we op dit moment al werken met een plus-min systeem voor de vaste werknemers, zijn er in de winter alsnog niet genoeg uren om grote aantallen vaste medewerkers uren te geven. Daarom zijn wij vaak op jongeren en gepensioneerden aangewezen om ons vaste team aan te vullen tijdens de piekmomenten.",
        "Jongeren hebben bijvoorbeeld vrij van school in de weekenden en vakanties en dit zijn nu juist de piekmomenten in de horeca. Daarom zal een groot deel van ons onderzoek ook gaan naar de vraag: \"Hoe kunnen wij jonger personeel werven?\"",
        "Ook gepensioneerden staan vaak open voor een oproepcontract omdat zij hun vaste lasten kunnen betalen door hun pensioen. Ze doen het werk dus vooral omdat zij dit leuk vinden en om iets extra's bij te verdienen. Daarnaast is het zowel voor de gast als voor de andere collega's leuk om te zien dat er een gevarieerd team is.",
        "Ook is het voor ons een mogelijkheid om studenten van een BBL horeca opleiding op te leiden. Zij zijn vaak beschikbaar en nemen vaak genoegen met een lager loon dan andere volwassenen omdat zij vaak nog thuis wonen en nog aan het studeren zijn. Het inkomen door het werk is dus vaak een gunstige bijkomstigheid. Een bijkomend voordeel voor ons is dat zij vaak meer kennis en ervaring hebben dan de gemiddelde student omdat zij over de horeca leren op school.",
        "Buiten het werven van nieuwe medewerkers, is het ook belangrijk om ervoor te zorgen dat onze huidige werknemers niet weggaan en een andere baan nemen. Toch is dit vaak onvermijdelijk omdat de meeste jongeren niet voor eeuwig in de horeca willen werken. Wel willen wij onze werknemers natuurlijk zo veel mogelijk behouden en zullen we dus ook hiernaar onderzoek doen.",
      ],
    },
    {
      id: "dv3-huidige-situatie",
      title: "Huidige situatie bij Rederij Cascade",
      paragraphs: [
        "De eerste manier waarop wij op dit moment personeel werven is door middel van onze website. De website die op onze website te vinden is, is erg beknopt. Het uurloon voor jongeren staat bijvoorbeeld nergens vermeld, terwijl zij dit vaak wel belangrijk vinden. Daarnaast is de drempel om te solliciteren erg hoog. Je moet namelijk een mail sturen om te solliciteren, wat voor veel jongeren lastig is en een obstakel kan zijn om daadwerkelijk te solliciteren.",
        "Daarnaast is er een onderverdeling gemaakt in horeca doordeweeks en horeca weekend, hoewel een scheiding hierin goed is, is deze onderverdeling niet uitgebreid genoeg en onlogisch. Mensen die doordeweeks beschikbaar zijn zouden namelijk ook in het weekend beschikbaar kunnen zijn. Daarnaast staat er niet meteen duidelijk aangegeven of het om een bijbaan of een vaste baan gaat. Dit zou er wellicht al voor kunnen zorgen dat mensen afhaken omdat ze denken dat ze niet geschikt zijn. Ook missen er een aantal functies; buiten horeca hebben we ook functies als kapitein, afwasser, keuken en entertainment.",
        "Buiten de eerste manier van personeelswerving kunnen er ook mogelijke sollicitanten doorverwezen worden door collega's, echter wordt dit nog niet actief door ons gepromoot en wordt deze manier dus weinig gebruikt.",
        "Op dit moment wordt er nog geen gebruikgemaakt van social media marketing. Ondanks het feit dat dit misschien niet de plek is waar mensen meteen op zoek zijn naar werk, zou het mensen wel kunnen informeren over ons bedrijf en kan het de drempel om te solliciteren voor jongeren verlagen omdat dit wat informeler is.",
        "Uit de informatie hierboven valt te concluderen dat er op dit moment nog niet veel gedaan wordt aan het werven van personeel en dat hier nog veel winst te behalen valt.",
      ],
    },
    {
      id: "dv3-concurrentie",
      title: "Aanpak van de concurrentie",
      paragraphs: [
        "Vaak kan het handig zijn om te kijken naar de concurrentie om te kijken welke mogelijkheden er zijn en wat voor ons het beste zou kunnen werken. Omdat er in de buurt weinig rederijen zijn, zullen we iets breder kijken naar andere bedrijven binnen de recreatie.",
        "De Zilvermeeuw is een rondvaartbedrijf dat rondvaarten uitvoert rondom en door het Biesbosch. Het bedrijf is vergelijkbaar met dat van ons, maar de schaal van hun bedrijf is wel een stuk groter. Op dit moment hebben zij namelijk 7 schepen in de vaart waarbij ze een maximale capaciteit van 978 personen hebben. Om dit te realiseren hebben ze dan ook ongeveer 130 werknemers in dienst. Wij varen op dit moment met 2 schepen waarmee we een maximale capaciteit van 400 personen kunnen behalen. Wij werken hier met ongeveer 40 medewerkers.",
        "Wanneer je op de hoofdpagina van de Zilvermeeuw komt, zie je bovenaan de website meteen een kopje \"Werken bij Zilvermeeuw\". Als je hierop doorklikt zie je meteen een verdeling in 3 categorieën: Horeca medewerker, medewerker keuken en Meeloop-stage receptie en ontvangst. Als je verder klikt op 1 van deze categorieën, dan zie je dat de gegeven informatie vrij beperkt is en dat solliciteren niet eenvoudig is, ook zij werken met een e-mail. Verder maken ze op social media geen reclame om bij hen te komen werken.",
        "Hoewel de informatie bij de Zilvermeeuw ook niet perfect weergegeven is, zijn er toch een aantal dingen die we van hen kunnen leren. Zo is de pagina van \"Werken bij\" duidelijk zichtbaar op de hele website. Ook geven ze de mogelijkheid om te bellen.",
        "Na de Zilvermeeuw gaan we kijken naar het beleid van Toverland. Zij liggen namelijk niet ver van Rederij Cascade en hebben ook last van veel pieken en dalen in bezoekersaantallen. Daarnaast hebben grote bedrijven vaak speciale mensen die verantwoordelijk zijn voor recruitment.",
        "Als je op de homepage van Toverland kijkt, dan zie je meteen rechtsboven een kopje \"vacatures\". Eenmaal aangekomen op de vacaturepagina zie je dat je bent doorgelinkt naar een aparte website. Deze website heeft een aantal hoofdkoppen: vacatures, wie zijn wij, alles over je bijbaan en bbl-opleiding. Op deze pagina's wordt uitgelegd dat er drukke en rustige periodes zijn, medewerkers met ervaringen uit Toverland aan het woord, zie je welke banen er bij Toverland allemaal zijn en zie je waaraan jij moet voldoen om bij Toverland te werken. Ook staan de basisuurlonen duidelijk vermeld.",
        "Ook heeft Toverland de categorie \"Bbl-opleiding\". Ze bieden zelfs een eigen opleiding aan in samenwerking met andere bedrijven in de buurt. Ondanks dat een eigen opleiding voor ons onhaalbaar is, zou het toch handig kunnen zijn om iets over bbl-leerlingen op de website te zetten.",
        "Per baan staat er een uitgebreide, maar duidelijke tekst met wat je werkzaamheden kunnen zijn en wat je kan verwachten. Mocht je overgehaald zijn om te solliciteren, dan kom je op een nieuwe pagina op dezelfde website waar je jouw gegevens, capaciteiten en motivatie kan invullen. Ook kan je je aanmelden voor een informatieavond en zie je de beschikbaarheid richtlijnen. Dit maakt het sollicitatieproces zeer eenvoudig.",
        "Buiten de website doet Toverland ook veel met advertenties op social media en in het park. Zo zijn er door het park heen posters te vinden met reclame om te werken bij Toverland. Het mooie hieraan is dat deze promotie verder geen kosten oplevert. Het posterconcept zouden we wel eenvoudig kunnen uitvoeren, bijvoorbeeld op de wc of op de gang.",
        "Tenslotte gaan wij kijken naar het beleid van de Jumbo in Maasbracht. Zij liggen in onze directe omgeving en concurreren dus direct met ons op de arbeidsmarkt. Als je de vacatures voor de Jumbo in Maasbracht bekijkt, zie je dat ze 4 functies hebben: versmedewerker, bakker, kassa en vakkenvuller. Bij elke specifieke vacature vind je de bijbehorende minimale leeftijd en vereiste kwaliteiten. Ook staat het loon duidelijk vermeld, maar dit is een stuk lager dan bij ons.",
        "Een opvallend ding in het formulier is \"Wie vertelde je over deze bijbaan?\". Dit zou kunnen betekenen dat medewerkers die nieuwe collega's meebrengen een extra bonus krijgen. Hier zouden wij ook mee kunnen werken, vooral omdat je hierbij alleen kosten maakt als er daadwerkelijk een nieuwe medewerker in dienst treedt.",
        "Door het analyseren van het beleid van de Jumbo weten wij onze sterke punten ten opzichte van de Jumbo beter: een hoger loon, een unieke werklocatie, een kleiner team waardoor je een betere band hebt met je collega's en flexibele beschikbaarheid. Je kan bij ons zelf tot maximaal 3 weken van tevoren aangeven of je beschikbaar bent of niet.",
        "Toch kleven er een aantal nadelen aan werken bij Rederij Cascade. De werkdruk zal tijdens piekmomenten namelijk hoger zijn dan bij een supermarkt of krantenwijk. Daarnaast verwachten we een serieuze inzet en kan het werk soms uitdagend zijn. Een ander nadeel is dat we niet jaarrond evenveel uren kunnen aanbieden.",
        "Ook is het belangrijk dat we ons personeel ook behouden. Op dit moment krijgen medewerkers die langer bij ons werken een toeslag per uur. Doordat ze meer verdienen, zullen ze minder snel een andere baan zoeken. Ook krijgt ons personeel de kans om zich te ontwikkelen en hun functies uit te breiden. Er gaan dan ook weinig werknemers bij ons weg.",
      ],
    },
    {
      id: "dv3-conclusie-analyse",
      title: "Conclusie analyse",
      paragraphs: [
        "Op basis van de huidige situatie bij Rederij Cascade en de vergelijking met de aanpak van andere bedrijven binnen de recreatiebranche kunnen wij concluderen dat het personeel wervingsbeleid op dit moment nog beperkt is ingericht en daardoor niet optimaal wordt benut. Met name de website vormt een belangrijke zwakke plek: belangrijke informatie over functies, type dienstverband en loon ontbreekt, waardoor potentiële sollicitanten, vooral jongeren, sneller afhaken. Daarnaast ligt de drempel om te solliciteren hoog doordat dit alleen via e-mail kan en er geen gebruik wordt gemaakt van een laagdrempelig sollicitatieformulier.",
        "Uit de analyse van de concurrentie blijkt dat andere bedrijven hier verder in zijn. De Zilvermeeuw laat zien hoe belangrijk het is dat de pagina \"werken bij\" duidelijk zichtbaar is op de website en dat er meerdere manieren zijn om contact op te nemen. Toverland gaat hierin nog een stap verder door uitgebreide informatie te geven over werken binnen het bedrijf, duidelijke arbeidsvoorwaarden te communiceren en het sollicitatieproces zo eenvoudig mogelijk te maken. Jumbo Maasbracht laat zien dat het duidelijk benoemen van loon en het inzetten van bestaande medewerkers bij het aandragen van nieuwe collega's effectief kan zijn.",
        "Voor Rederij Cascade betekent dit dat er veel ruimte is voor verbetering. Door de website overzichtelijker en informatiever te maken, alle functies duidelijk te presenteren en het sollicitatieproces te vereenvoudigen, kan de drempel om te solliciteren aanzienlijk worden verlaagd. Daarnaast bieden social media, interne promotie en het actiever inzetten van medewerkers als doorverwijzers kansen om zonder grote kosten meer potentiële sollicitanten te bereiken.",
        "Tot slot blijkt uit de vergelijking dat Rederij Cascade sterke punten heeft ten opzichte van de concurrentie, zoals een hoger loon dan bijvoorbeeld de Jumbo, een unieke werklocatie en een klein, hecht team met flexibele beschikbaarheid. Door deze voordelen beter te benadrukken en het wervingsbeleid te professionaliseren, kan Rederij Cascade zich sterker positioneren op de arbeidsmarkt.",
      ],
    },
    {
      id: "dv3-plan",
      title: "Plan van aanpak",
      paragraphs: [
        "Nu we weten wat onze huidige zwakke en sterke punten zijn en op de hoogte zijn van wat andere bedrijven doen om voldoende personeel te werven, kunnen we een plan van aanpak maken zodat we een goed personeelsbeleid kunnen opstellen.",
        "Wij zorgen ervoor dat sollicitanten zich makkelijk kunnen aanmelden via een eigen vacaturewebsite. Geïnspireerd door de aanpak van Toverland, die een aparte \"Werken bij\" website heeft, hebben wij besloten om zelf ook een professionele vacaturesite te bouwen. Deze website bevat niet alleen een overzichtelijke lijst met alle beschikbare vacatures, maar ook een laagdrempelig sollicitatieformulier waarin de sollicitant zijn of haar gegevens, functievoorkeur, ervaring, talenkennis en beschikbaarheid kan invullen. Daarnaast bevat de site pagina's zoals \"Jouw bijbaan\" en \"Over ons\", waar potentiële sollicitanten meer kunnen lezen over hoe het is om bij Rederij Cascade te werken. Ook worden de loontabellen per leeftijd en functie duidelijk weergegeven. Aan de achterkant beschikt de website over een admin dashboard waarmee wij binnengekomen sollicitaties kunnen beheren, vacatures kunnen aanmaken en bewerken, en paginateksten via een CMS kunnen aanpassen. De website is te vinden op werkenbijcascade.nl.",
        "Daarnaast zullen wij een pdf maken met een mooie, overzichtelijke presentatie van de beschikbaarheidseisen. Dit doen wij zodat wij op de piekmomenten genoeg personeel hebben en zodat het personeel duidelijk weet wat er van hen verwacht wordt met betrekking tot beschikbaarheid.",
        "Verder zullen we de tekst op de website herschrijven en zo nodig extra informatie toevoegen zodat het voor de sollicitant duidelijker is wat er van hem of haar verwacht wordt. Ook delen we het op in 6 categorieën: bediening/bar, keuken, afwas, kapitein en matroos. Daarbij vermelden we ook dat er een neventaak mogelijk is in ons entertainment team.",
        "Wij willen onze medewerkers eenmalig een bepaald bedrag geven als zij iemand doorverwijzen die bij ons in dienst komt en voldoet aan een aantal voorwaarden. Dit kan jongeren aansporen om hun vrienden te activeren om ook bij ons te komen werken. Wel is het belangrijk dat ze minimaal 3 maanden in dienst blijven en zich houden aan de beschikbaarheid richtlijnen.",
        "Het is belangrijk om niet alleen te kijken naar het verbeteren van de instroom, maar ook naar het behoud van werknemers. Op dit moment zijn er weinig werknemers die bij ons uit dienst gaan. We zullen ons huidige beleid dus doorzetten. Zo zorgen we voor bonussen, genoeg doorgroeimogelijkheden en werken we zoveel mogelijk mee met de wensen van het personeel.",
        "Op onze schepen lopen veel gasten waarvan sommige wellicht ook bij ons zouden willen werken. Als we een poster ophangen, bijvoorbeeld op de wc of in de gang, dan zou dit mensen kunnen aanzetten tot sollicitatie. Het is belangrijk om hierbij aan te geven dat je zelf je beschikbaarheid kan bepalen en dat het voor jong en oud is.",
      ],
    },
    {
      id: "dv3-uitvoering",
      title: "Uitvoering",
      paragraphs: [
        "Als uitvoering van het plan van aanpak hebben wij een volledige vacaturewebsite gebouwd, te vinden op werkenbijcascade.nl. Deze website is speciaal ontwikkeld voor Rederij Cascade en bevat alles wat nodig is om het sollicitatieproces professioneel en laagdrempelig te maken. Het resultaat van ons onderzoek is daarmee niet alleen beschreven in dit werkstuk, maar ook daadwerkelijk zichtbaar en bruikbaar in de praktijk.",
        "De website bevat de volgende publieke onderdelen: Een overzichtelijke vacaturelijst met alle beschikbare functies, onderverdeeld in categorieën zoals bediening/bar, keuken, afwas, kapitein en matroos. Een laagdrempelig sollicitatieformulier waarin sollicitanten hun persoonlijke gegevens, functievoorkeur, ervaring, talenkennis en beschikbaarheid kunnen invullen. Dit vervangt de hoge drempel van solliciteren via e-mail. Daarnaast bevat de site een pagina \"Jouw bijbaan\" met informatie over werken bij Rederij Cascade, vergelijkbaar met de aanpak van Toverland. Ook is er een pagina over BBL-opleidingen, zodat leerlingen die een horeca-opleiding volgen weten dat ze bij ons terechtkunnen. Loontabellen per leeftijd en functie worden duidelijk weergegeven, zodat sollicitanten direct kunnen zien wat ze verdienen — een belangrijk concurrentievoordeel ten opzichte van bijvoorbeeld de Jumbo. Tot slot is er een \"Over ons\" pagina die de sfeer en het team van Rederij Cascade laat zien.",
        "Achter de schermen beschikt de website over een admin dashboard waarmee wij binnengekomen sollicitaties kunnen inzien en beheren, vacatures kunnen aanmaken en bewerken, loontabellen kunnen bijwerken en paginateksten kunnen aanpassen via een ingebouwd CMS. Hierdoor kan Rederij Cascade de website volledig zelfstandig beheren zonder technische kennis.",
        "Om de beoordelaar de mogelijkheid te geven om het resultaat te bekijken, is er een viewer-account aangemaakt waarmee kan worden ingelogd op het admin dashboard van werkenbijcascade.nl. Zo kan de volledige achterkant van de website bekeken worden, inclusief het sollicitatiebeheer, de vacature-editor en het CMS. De inloggegevens zijn te vinden op de volgende pagina van dit werkstuk.",
      ],
    },
    {
      id: "dv3-conclusie",
      title: "Conclusie",
      paragraphs: [
        "Op basis van ons onderzoek kunnen wij de onderzoeksvraag als volgt beantwoorden: Rederij Cascade kan in de huidige arbeidsmarkt voldoende en geschikt personeel aantrekken door het wervingsbeleid te professionaliseren en de drempel om te solliciteren te verlagen.",
        "Uit de analyse van de huidige situatie bleek dat de personeelswerving bij Rederij Cascade nog beperkt was ingericht. De vacatures op de website waren onvolledig, het sollicitatieproces verliep uitsluitend via e-mail en belangrijke informatie zoals loon, type dienstverband en functieomschrijvingen ontbrak. Door dit te vergelijken met de aanpak van de Zilvermeeuw, Toverland en de Jumbo Maasbracht konden wij concrete verbeterpunten identificeren.",
        "Het plan van aanpak richtte zich op vier onderdelen: een professionele presentatie van vacatures via een eigen vacaturewebsite, interne promotie via een doorverwijzingsbonus, behoud van medewerkers door het huidige beleid voort te zetten en fysieke promotie op de schepen. De kern van de uitvoering is de vacaturewebsite werkenbijcascade.nl, die wij zelf hebben gebouwd. Deze website combineert de best practices van de geanalyseerde bedrijven: een laagdrempelig sollicitatieformulier zoals bij Toverland, duidelijke loontabellen zoals bij de Jumbo en een overzichtelijke vacaturelijst met alle functies.",
        "Door deze aanpak is Rederij Cascade beter voorbereid om in de krappe arbeidsmarkt voldoende personeel aan te trekken, zonder de flexibiliteit en persoonlijke sfeer van het bedrijf te verliezen.",
      ],
    },
  ],
};
